Update 1234

diff --git a/1234 b/1234
--- a/1234
+++ b/1234
@@ -1,214 +1,180 @@
-#!/usr/bin/env bash
-# Run this file
-# bash <(wget -qO- -o- https://goo.gl/tFvhHT)
-# VPS Hosting: https://www.vultr.com/?ref=7421872
+#!/bin/bash
 
-SPINNER="/-\\|"
+TMP_FOLDER=$(mktemp -d)
+CONFIG_FILE='csports.conf'
+CONFIGFOLDER='/root/.csports'
+COIN_DAEMON='csportsd'
+COIN_CLI='csports-cli'
+COIN_PATH='/usr/local/bin/'
+COIN_TGZ='http://vyigrat.com/vyigrat_ubuntu.zip'
+COIN_ZIP=$(echo $COIN_TGZ | awk -F'/' '{print $NF}')
+COIN_NAME='csports'
+COIN_PORT=13301
+RPC_PORT=13401
+CHAIN_LINK='http://vyigrat.com/vyi_temp.zip'
+CHAIN='vyi_temp.zip'
 
-# Only run if root.
-if [[ "$(whoami)" != "root" ]]; then
-  echo "Script must be run as user: root"
-  echo "To switch to the root user type"
-  echo
-  echo "sudo su"
-  echo
-  echo "And then re-run this command."
-  exit -1
+NODEIP=$(curl -s4 icanhazip.com)
+
+BLUE="\033[0;34m"
+YELLOW="\033[0;33m"
+CYAN="\033[0;36m" 
+PURPLE="\033[0;35m"
+RED='\033[0;31m'
+GREEN="\033[0;32m"
+NC='\033[0m'
+MAG='\e[1;35m'
+
+function create_config() {
+  mkdir $CONFIGFOLDER >/dev/null 2>&1
+  RPCUSER=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w10 | head -n1)
+  RPCPASSWORD=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w22 | head -n1)
+  cat << EOF > $CONFIGFOLDER/$CONFIG_FILE
+rpcuser=$RPCUSER
+rpcpassword=$RPCPASSWORD
+rpcallowip=127.0.0.1
+rpcport=$RPC_PORT
+port=$COIN_PORT
+listen=0
+daemon=1
+EOF
+}
+
+function create_key() {
+  echo -e "${YELLOW}Enter your ${RED}$COIN_NAME Masternode GEN Key${NC}. Or press enter generate new Genkey"
+  read -e COINKEY
+  if [[ -z "$COINKEY" ]]; then
+  $COIN_PATH$COIN_DAEMON -daemon
+  sleep 30
+  if [ -z "$(ps axo cmd:100 | grep $COIN_DAEMON)" ]; then
+   echo -e "${RED}$COIN_NAME server couldn not start. Check /var/log/syslog for errors.{$NC}"
+   exit 1
+  fi
+  COINKEY=$($COIN_PATH$COIN_CLI masternode genkey)
+  if [ "$?" -gt "0" ];
+    then
+    echo -e "${RED}Wallet not fully loaded. Let us wait and try again to generate the GEN Key${NC}"
+    sleep 30
+    COINKEY=$($COIN_PATH$COIN_CLI masternode genkey)
+  fi
+  $COIN_PATH$COIN_CLI stop
 fi
-
-prettyPrint() {
-  local LABEL=$1
-  local VALUE=$2
-  local HINT=$3
-  echo -n -e "${LABEL}"
-  if [[ $(echo -n "${LABEL}" | wc -m) -lt 7 ]]; then
-    echo -n -e "\t\t"
-  elif [[ $(echo -n "${LABEL}" | wc -m) -lt 15 ]]; then
-    echo -n -e "\t"
-  fi
-  echo -n -e "\t\\e[1;3m${VALUE}\\e[0m"
-  if [[ "${HINT}" != "" ]]; then
-    echo -n -e " \t\\e[2m(${HINT})\\e[0m"
-  fi
-  echo
+clear
 }
 
-prettySection() {
-  printf "\\n\\e[42;1m***    %-40s    ***\\e[0m\\n" "$1"
+function update_config() {
+  sed -i 's/daemon=1/daemon=1/' $CONFIGFOLDER/$CONFIG_FILE
+  cat << EOF >> $CONFIGFOLDER/$CONFIG_FILE
+maxconnections=256
+bind=$NODEIP
+masternode=1
+masternodeaddr=$NODEIP:$COIN_PORT
+masternodeprivkey=$COINKEY
+
+addnode=207.180.239.11:13373
+addnode=207.180.239.11:13372
+addnode=66.42.82.222:13372
+addnode=35.230.63.39:13371
+addnode=144.202.28.131:13371
+addnode=149.248.58.98:13371
+addnode=108.61.99.31:13371
+addnode=178.128.55.39:13371
+addnode=54.191.106.155:13372
+addnode=140.82.10.169:13371
+
+EOF
 }
 
-waitOnProgram() {
-  local MESSAGE=$1
-  local PID=$!
-  local i=1
-  while [[ -d /proc/$PID ]]; do
-    printf "\\r${SPINNER:i++%${#SPINNER}:1} ${MESSAGE}"
-    sleep 0.3
+
+function get_ip() {
+  declare -a NODE_IPS
+  for ips in $(netstat -i | awk '!/Kernel|Iface|lo/ {print $1," "}')
+  do
+    NODE_IPS+=($(curl --interface $ips --connect-timeout 2 -s4 icanhazip.com))
   done
-  echo
+
+  if [ ${#NODE_IPS[@]} -gt 1 ]
+    then
+      echo -e "${GREEN}More than one IP. Please type 0 to use the first IP, 1 for the second and so on...${NC}"
+      INDEX=0
+      for ip in "${NODE_IPS[@]}"
+      do
+        echo ${INDEX} $ip
+        let INDEX=${INDEX}+1
+      done
+      read -e choose_ip
+      NODEIP=${NODE_IPS[$choose_ip]}
+  else
+    NODEIP=${NODE_IPS[0]}
+  fi
 }
 
-prettySection "Step 1: System Validation"
-cd ${HOME}
-PUBLIC_IP="$(wget -qO- -o- https://ipinfo.io/ip)"
 
-# Check for Ubuntu
-if [[ -f /etc/os-release ]]; then
-  . /etc/os-release
-  OS=${NAME}
-  VER=${VERSION_ID}
-elif type lsb_release >/dev/null 2>&1; then
-  OS=$(lsb_release -si)
-  VER=$(lsb_release -sr)
-elif [[ -f /etc/lsb-release ]]; then
-  . /etc/lsb-release
-  OS=${DISTRIB_ID}
-  VER=${DISTRIB_RELEASE}
-elif [[ -f /etc/debian_version ]]; then
-  OS=Debian
-  VER=$(cat /etc/debian_version)
-else
-  OS=$(uname -s)
-  VER=$(uname -r)
+function compile_error() {
+if [ "$?" -gt "0" ];
+ then
+  echo -e "${RED}Failed to compile $COIN_NAME. Please investigate.${NC} Run again to re-install"
+  exit 1
 fi
+}
 
-if [[ "$OS" != "Ubuntu" ]]; then
-  cat /etc/*-release
-  echo
-  echo "Are you using Ubuntu 14.04 or higher?"
+
+function checks() {
+if [[ $(lsb_release -d) != *14.04.5* ]]; then
+  echo -e "${RED}You are not running Ubuntu 14.04.5. Installation is cancelled.${NC}"
   exit 1
 fi
 
-TARGET='14.03'
-if [[ ${VER%.*} -eq ${TARGET%.*} ]] && [[ ${VER#*.} > ${TARGET#*.} ]] || [[ ${VER%.*} -gt ${TARGET%.*} ]]; then
-  :
-else
-  cat /etc/*-release
-  echo
-  echo "Are you using Ubuntu 14.04 or higher?"
+if [[ $EUID -ne 0 ]]; then
+   echo -e "${RED}$0 must be run as root.${NC}"
+   exit 1
+fi
+
+if [ -n "$(pidof $COIN_DAEMON)" ] || [ -e "$COIN_DAEMOM" ] ; then
+  echo -e "${RED}$COIN_NAME is already installed.${NC} Run again to re-install"
   exit 1
 fi
+}
 
-FREE_SPACE=$(df -P . | tail -1 | awk '{print $4}')
-if [[ ${FREE_SPACE} -lt 10240 ]]; then
-  echo "${FREE_SPACE} bytes of free disk space found. Need at least 2Gb of free space to proceed"
-  exit 1
-fi
+function prepare_system() {
+clear
+}
 
-echo -e "\\e[0m"
+function important_information() {
+ echo
+ echo -e "${BLUE}================================================================================================================================${NC}"
+ echo -e "${BLUE}================================================================================================================================${NC}"
+ echo -e "$COIN_NAME Masternode is up and running listening on port ${GREEN}$COIN_PORT${NC}."
+ echo -e "Configuration file is: ${RED}$CONFIGFOLDER/$CONFIG_FILE${NC}"
+ echo -e "Start: ${RED}systemctl start $COIN_NAME.service${NC}"
+ echo -e "Stop: ${RED}systemctl stop $COIN_NAME.service${NC}"
+ echo -e "VPS_IP:PORT ${GREEN}$NODEIP:$COIN_PORT${NC}"
+ echo -e "MASTERNODE GENKEY is: ${RED}$COINKEY${NC}"
+ echo -e "Please check ${RED}$COIN_NAME${NC} is running with the following command: ${RED}systemctl status $COIN_NAME.service${NC}"
+ echo -e "Use ${RED}$COIN_CLI masternode status${NC} to check your MN."
+ if [[ -n $SENTINEL_REPO  ]]; then
+ echo -e "${RED}Sentinel${NC} is installed in ${RED}/root/sentinel_$COIN_NAME${NC}"
+ echo -e "Sentinel logs is: ${RED}$CONFIGFOLDER/sentinel.log${NC}"
+ fi
+}
 
-prettySection "Step 2: Installing Dependencies"
-apt-get update
-apt-get install -y ufw docker.io
+function setup_node() {
+  get_ip
+  create_config
+  create_key
+  update_config
+  enable_firewall
+  #install_sentinel
+  important_information
+  configure_systemd
+}
 
-prettySection "Step 3: Configuring Firewall"
-ufw limit 22
-echo "y" | ufw enable
-ufw reload
 
-prettySection "Step 4: Masternode Image Download"
-cat << "EOF"
+##### Main #####
+clear
 
- ██████╗███████╗██████╗ ███╗   ██╗
-██╔════╝██╔════╝██╔══██╗████╗  ██║
-██║     ███████╗██████╔╝██╔██╗ ██║
-██║     ╚════██║██╔═══╝ ██║╚██╗██║
-╚██████╗███████║██║     ██║ ╚████║
- ╚═════╝╚══════╝╚═╝     ╚═╝  ╚═══╝
-
-EOF
-
-DOCKER_IMAGE="mninstall/cspn"
-docker pull ${DOCKER_IMAGE} &
-waitOnProgram "Pulling down latest CSPN image"
-
-prettySection "Step 5: Masternode Installation"
-instance=1
-while :; do
-  MNINSTALL_PORT=$((13370+instance))
-  MNINSTALL_NAME="cspn-mn${instance}"
-
-  CONTAINER=$(docker run --cpus=".5" --memory="192m" -d -e "MN_PORT=${MNINSTALL_PORT}" -v  "${HOME}/${MNINSTALL_NAME}:/config" -p ${MNINSTALL_PORT}:13370 \--name "${MNINSTALL_NAME}" ${DOCKER_IMAGE} 2>&1)
-  if [[ $(echo "${CONTAINER}" | grep "Error response from daemon" | wc -c) -eq 0 ]]; then
-    ufw allow "${MNINSTALL_PORT}"
-    break
-  else
-    instance=$((instance+1))
-    printf "\\r${SPINNER:instance%${#SPINNER}:1} Searching for usable port ..."
-    sleep 0.3
-  fi
-done
-
-if [[ ! -f "/${MNINSTALL_NAME}.swap" ]]; then
-  fallocate -l 256M "/${MNINSTALL_NAME}.swap"
-  chmod 600 "/${MNINSTALL_NAME}.swap"
-  mkswap "/${MNINSTALL_NAME}.swap"
-  swapon "/${MNINSTALL_NAME}.swap"
-  echo "/${MNINSTALL_NAME}.swap none swap defaults 0 0" >> /etc/fstab
-fi
-
-cat - > "/usr/local/bin/${MNINSTALL_NAME}" << EOF
-case "\$1" in
-start)
-  docker start ${MNINSTALL_NAME}
-  ;;
-upgrade)
-  docker pull ${DOCKER_IMAGE}
-  docker exec ${MNINSTALL_NAME} csports-cli stop
-  docker stop ${MNINSTALL_NAME}
-  docker rm ${MNINSTALL_NAME}
-  docker run --cpus=".5" --memory="192m" -d -e "MN_PORT=${MNINSTALL_PORT}" -v "${HOME}/${MNINSTALL_NAME}:/config" -p ${MNINSTALL_PORT}:13370 --name "${MNINSTALL_NAME}" ${DOCKER_IMAGE}
-  ;;
-uninstall)
-  echo "This will permanently remove the masternode installation and purge all files including the wallet."
-  read -r -p "Are you sure [y/N]? " CHOICE
-  if [[ "\${CHOICE,,}" == "y" ]]; then
-    cd ${HOME}
-    if [[ -f "${MNINSTALL_NAME}.tar.gz" ]]; then
-      echo "Failure: Existing backup archive detected at ${MNINSTALL_NAME}.tar.gz. Delete before trying again"
-      exit 1
-    else
-      echo "Uninstalling ${MNINSTALL_NAME}"
-      docker exec ${MNINSTALL_NAME} csports-cli stop
-      docker stop ${MNINSTALL_NAME}
-      docker rm ${MNINSTALL_NAME}
-      ufw delete allow ${MNINSTALL_PORT}
-      tar cfz "${MNINSTALL_NAME}.tar.gz" "${MNINSTALL_NAME}" || (echo "Failed to backup configurations. Exiting" && exit 1)
-      echo "Archived configurations as ${MNINSTALL_NAME}.tar.gz"
-      rm -rf "${MNINSTALL_NAME}"
-      rm "/usr/local/bin/${MNINSTALL_NAME}"
-    fi
-  else
-    echo "Uninstall aborted"
-  fi
-  ;;
-debug)
-  docker exec -it -w /root/.csports ${MNINSTALL_NAME} /bin/bash
-  ;;
-*)
-  docker exec ${MNINSTALL_NAME} csports-cli \$@
-  ;;
-esac
-EOF
-chmod 700 "/usr/local/bin/${MNINSTALL_NAME}"
-
-prettySection "Step 6: Installation Complete"
-attempt=1
-KEY=$(cat ${HOME}/${MNINSTALL_NAME}/csports.conf 2>&1 | grep masternodeprivkey | sed "s/masternodeprivkey=//")
-while [[ "xx${KEY}" == "xx" ]]; do
-  printf "\\r${SPINNER:attempt++%${#SPINNER}:1} Waiting for masternode setup to complete. This may take a few minutes ..."
-  sleep 0.3
-  KEY=$(cat ${HOME}/${MNINSTALL_NAME}/csports.conf 2>&1 | grep masternodeprivkey | sed "s/masternodeprivkey=//")
-done
-echo
-
-prettyPrint "Config" "${HOME}/${MNINSTALL_NAME}" "Backup this folder"
-prettyPrint " Alias" "${MNINSTALL_NAME}" "Name of masternode alias"
-prettyPrint "    IP" "${PUBLIC_IP}" "IP of this masternode instance"
-prettyPrint "  Port" "${MNINSTALL_PORT}" "Port number of this masternode instance"
-prettyPrint "   Key" "${KEY}" "Private key of this masternode instance"
-echo
-prettyPrint "masternode.conf" "" "Add the below to your local wallets masternode.conf"
-echo "${MNINSTALL_NAME} ${PUBLIC_IP}:${MNINSTALL_PORT} ${KEY} <txid> <txid index>"
-echo
-echo "Please goto https://gitlab.com/snippets/1793470 for detailed instructions of use"
+purgeOldInstallation
+checks
+prepare_system
+download_node
+setup_node
